
- name: Update the interface with their parents
  set_fact:
    interfaces: "{{ lookup('add_defaults', interfaces, hostvars[inventory_hostname] ) }}"

- name: Switch to OS specific files and templates
  include: "{{ '%s-interface.yml' % os }}"
  with_items: "{{ interfaces }}"
